### ISSUE TITLE
Use `std::io::BufWriter` to achieve more flexibility

### ISSUE THREAD

**Issue by giulio-Joshi** [anas-elgarhy/aarty#4]
Hello everyone! 

I found your awesome project in the Hacktoberfest Discord, I hope my contribution can be of help.

I'm unsure in which direction the project can be expanded, so I attempted at making it more flexible in general: using a `BufWriter` to apply Inversion of Control on the `generate_ascii` function.

You can check the code on my branch:
https://github.com/giulio-Joshi/aarty/tree/bufferedOutput

Before barging in with a PR directly, I opted for asking some feedback about it. 

Thanks a lot for your time 👍🏻

**Comment by anas-elgarhy** [comment]
I liked your edits, and it faster than original method that's I use

**Comment by anas-elgarhy** [comment]
I have learned new ways to think from you, thanks
